/* ============================================================
   CONFIG.JS — Funnel Listicle Veloura
   ============================================================ */
window.FUNNEL_CONFIG = {
  supabaseUrl: 'https://mjkbobemvirtfioanbxu.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qa2JvYmVtdmlydGZpb2FuYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODgyMDUsImV4cCI6MjA5MTY2NDIwNX0.d1UnuY-TYq8molxjwJBKBdmlBT5xeM3ZUjZQ-4UsB14',
  funnelId: 'listicle',
  adminPassword: 'admin2026',
  metaPixelId: '',
  gaId: '',
  ctaUrl: 'https://example.com',
  itemsEnabled: { item1:true, item2:true, item3:true, item4:true, item5:true, item6:true, item7:true, item8:true, item9:true, item10:true },
  colors: { '--bg':'#FFFFFF','--pink-accent':'#E3A7C4','--pink-deep':'#C7849A','--pink-light':'#F3D6DE','--pink-gradient-end':'#FBE8EE','--coral':'#EA9393','--text-dark':'#151515','--text-near-black':'#121212','--text-body':'#444444','--text-muted':'#6B6060','--text-light':'#888888','--border-light':'#EEEEEE','--navy-dark':'#1A1B2E','--pink-line':'#E94C7F','--cream':'#FAF4F0','--sponsor-text':'#6B7280','--footer-text':'#B5B5C8','--footer-copy':'#8A8AA0','--cta-bg':'#E3A7C4','--cta-text':'#FFFFFF' },
  fonts: { headline:'Inter', body:'Inter', logo:'Playfair Display', marquee:'Questrial' },
  images: { author:'', hero:'', item1:'', item2:'', item3:'', item4:'', item5:'', item6:'', item7:'', item8:'', item9:'', item10:'' },
  texts: {
    magazineName:'Eclat', magazineNameItalic:'Magazine',
    sponsorBarText:'Article sponsorisé · Partenariat avec Veloura France',
    footerAboutText:'Eclat Magazine est un magazine indépendant. Cet article est sponsorisé par Veloura France et a été rédigé en partenariat éditorial.',
    footerCopyright:'© 2026 Eclat Magazine · Tous droits réservés',
    heroCategory:'Bien-être · Santé féminine',
    h1:'Les femmes avisées abandonnent les serviettes jetables pour les <em>serviettes en coton lavables</em>… voici pourquoi',
    heroSubtitle:"Pendant que vous continuez avec les mêmes produits d'incontinence qui vous déçoivent, des milliers de femmes de votre âge ont découvert quelque chose de complètement différent.",
    heroCta:'Découvrir Veloura Pads', bylineAuthor:'Par Jessica M.', bylineDate:'Mis à jour le 3 février 2026',
    item1Title:'Vous méritez une protection qui vous traite comme une femme — pas comme une patiente',
    item1Text:"Les serviettes jetables promettent la discrétion mais donnent l'impression d'un produit médical dès qu'on les met. Veloura mise sur la dignité.",
    item2Title:'Elles tiennent toute la journée pour une vie active et pratique',
    item2Text:"Les culottes absorbantes vous enferment dans une couche humide toute la journée sans échappatoire.",
    item3Title:"Les serviettes de pharmacie intoxiquent votre peau et l'environnement",
    item3Text:"Les serviettes jetables se présentent comme sûres mais abîment votre corps et la planète à chaque usage.",
    item4Title:'100% coton, la SEULE matière qui devrait JAMAIS toucher votre peau la plus sensible',
    item4Text:"Les serviettes synthétiques promettent le confort mais piègent la chaleur, l'humidité et les PFAS.",
    item5Title:'Un système de boutons-pressions qui tient en place. Fini les glissements',
    item5Text:"Les serviettes lavables bon marché promettent de tenir, mais glissent dès que vous vous asseyez ou bougez.",
    item6Title:'Lavable en machine, conçue pour durer des années, et sans odeur',
    item6Text:"Les serviettes jetables vous obligent à racheter sans cesse, vident votre budget et s'entassent dans les décharges.",
    item7Title:"Un seul achat remplace des milliers d'euros en jetables",
    item7Text:"Les serviettes jetables semblent bon marché à 60 € par mois — jusqu'à ce que vous réalisiez que vous dépensez 720 € par an.",
    item8Title:"De vraies femmes de votre âge ont déjà fait le changement — et ne reviennent pas en arrière",
    item8Text:"Des milliers de femmes de 60 ans et plus ont essayé Veloura et ont eu la même réaction : la surprise que quelque chose fonctionne enfin.",
    item9Title:'En ce moment : une offre spéciale 1 acheté = 1 offert sur tous les packs',
    item9Text:"L'offre 1 acheté = 1 offert Veloura fonctionne sur n'importe quelle quantité — pack de 2 ou de 8.",
    item10Title:"Commandez n'importe quel pack et nous doublons GRATUITEMENT — mais le stock est presque épuisé",
    item10Text:"Veloura double votre commande gratuitement, sans minimum, sans piège — mais les derniers réassorts sont partis en 48 heures.",
    finalCtaText:'Vérifier la disponibilité',
    stickyCtaText:"Profiter de l'offre"
  }
};
